version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/baby_posture_analysis:latest
    container_name: baby_posture_analysis
    restart: always
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
      # Mount các file nhạy cảm từ host vào container (chúng sẽ ghi đè lên các file được tạo trong build)
      - ./.env:/app/.env
      # Không mount file credential - sẽ tạo từ biến môi trường FIREBASE_CREDENTIAL_BASE64
    environment:
      # Biến môi trường cho ứng dụng
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - API_TITLE=Baby Posture Analysis
      - API_DESCRIPTION=API for analyzing baby posture from images and videos
      - API_VERSION=1.0.0

      # Cấu hình Uvicorn
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8080
      - UVICORN_LOG_LEVEL=info
      - UVICORN_WS_PING_INTERVAL=30
      - UVICORN_WS_PING_TIMEOUT=120
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  app-network:
    driver: bridge
