name: Deploy Baby Posture Analysis to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create secret files
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          echo "${{ secrets.BABYCARE_CONNECTION_JSON }}" > babycare_connection.json

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/baby_posture_analysis:latest
          build-args: |
            ENV_FILE_CONTENT=${{ secrets.ENV_FILE_CONTENT }}
            BABYCARE_CONNECTION_JSON=${{ secrets.BABYCARE_CONNECTION_JSON }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Tạo thư mục dự án nếu chưa tồn tại
            mkdir -p ~/baby_posture_analysis
            
            # Dừng và xóa container cũ
            cd ~/baby_posture_analysis
            docker-compose down || true
            
            # Pull image mới nhất
            docker pull ${{ secrets.DOCKER_USERNAME }}/baby_posture_analysis:latest
            
            # Khởi động lại service
            docker-compose up -d 